// <autogenerated>
//   This file was generated by T4 code generator EntityCodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

//------------------------------------------------------------------------------
// <copyright file="IMenuService.cs">
//        Copyright(c)2013 QuestCN.All rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：溯汇软件@中国
//        公司网站：http://www.cnsuhui.com
//        所属工程：Quest.Core
//        生成时间：2016-08-18 09:39
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.Composition;
using Quest.Core.Data;
using Quest.Core.Models.Base;
using Quest.Framework;
using Quest.Framework.MVC;

namespace Quest.Core.Base
{
	/// <summary>
    /// 菜单 核心业务契约
    /// </summary>
    public partial interface IMenuService
    {
        #region 公共属性

        #endregion

        #region 公共方法

        OperationResult GetByParentName(String parentName = "root", MenuType mType = MenuType.Menu, MenuUse menuUse = MenuUse.PC);

        OperationResult GetByRoot(MenuType mType = MenuType.Menu, MenuUse menuUse = MenuUse.PC);
        #endregion

        #region 私有方法

        #endregion
    }
}
